import "./globals.css";
import { AuthProvider } from "../context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="navbar">
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          />
          {/* <div className="container">
            <img src="/images/logo.png" alt="Logo" className="logo" />
            <h1 className="title">Chatbot UI</h1>
          </div> */}
        </header>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
